### ISSUE TITLE
SECP256K1_SCHNORRSIG_EXTRAPARAMS_INIT does not work with C++

### ISSUE THREAD

**Issue by guidovranken** [bitcoin-core/secp256k1#962]
```c
#include <secp256k1.h>
#include <secp256k1_schnorrsig.h>

int main(void)
{
    secp256k1_schnorrsig_extraparams extraparams = SECP256K1_SCHNORRSIG_EXTRAPARAMS_INIT;
    return 0;
}
```

This compiles as C but not as C++.

clang++:

```
x.cpp:6:52: error: initializer-string for char array is too long
    secp256k1_schnorrsig_extraparams extraparams = SECP256K1_SCHNORRSIG_EXTRAPARAMS_INIT;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/secp256k1/include/secp256k1_schnorrsig.h:90:5: note: expanded from macro 'SECP256K1_SCHNORRSIG_EXTRAPARAMS_INIT'
    SECP256K1_SCHNORRSIG_EXTRAPARAMS_MAGIC,\
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/secp256k1/include/secp256k1_schnorrsig.h:88:48: note: expanded from macro 'SECP256K1_SCHNORRSIG_EXTRAPARAMS_MAGIC'
#define SECP256K1_SCHNORRSIG_EXTRAPARAMS_MAGIC "\xda\x6f\xb3\x8c"
                                               ^~~~~~~~~~~~~~~~~~
1 error generated.
```

g++

```
In file included from x.cpp:2:0:
x.cpp: In function ‘int main()’:
/secp256k1/include/secp256k1_schnorrsig.h:93:1: error: initializer-string for array of chars is too long [-fpermissive]
 }
 ^
x.cpp:6:52: note: in expansion of macro ‘SECP256K1_SCHNORRSIG_EXTRAPARAMS_INIT’
     secp256k1_schnorrsig_extraparams extraparams = SECP256K1_SCHNORRSIG_EXTRAPARAMS_INIT;
```

**Comment by real-or-random** [comment]
I guess there's an unwritten rule that the include files should work in C++ too... Maybe we should test this in CI. 

Here's a related CI failure after merging the same PR #844 (when CI was running on the PR, we didn't have `-Werror` yet...), which doesn't deserve an issue on its own:
https://github.com/bitcoin-core/secp256k1/runs/2978402299

cc @jonasnick

**Comment by gmaxwell** [comment]
LGTM.  Maybe you should add a CI build that builds the entire project/tests/benchmarks with a C++ compiler-- it should compile. It may need -fpermissive or a few extra explicit casts.  (Don't use Werror, though).
