### ISSUE TITLE
compile warnings after <string.h> include removed

### ISSUE THREAD

**Issue by paveljanik** [bitcoin-core/secp256k1#409]
After removal of `string.h` include (https://github.com/bitcoin-core/secp256k1/commit/a6c6f994b55619154fda3de20527dc560b8ca1ed):

```
In file included from src/tests.c:16:
In file included from ./src/secp256k1.c:14:
./src/ecmult_impl.h:186:9: warning: implicitly declaring library function
      'memcpy' with type 'void *(void *, const void *, unsigned long)'
        memcpy(dst->pre_g, src->pre_g, size);
        ^
./src/ecmult_impl.h:186:9: note: include the header <string.h> or explicitly
      provide a declaration for 'memcpy'
./src/ecmult_impl.h:230:5: warning: implicitly declaring library function
      'memset' with type 'void *(void *, int, unsigned long)'
    memset(wnaf, 0, len * sizeof(wnaf[0]));
    ^
./src/ecmult_impl.h:230:5: note: include the header <string.h> or explicitly
      provide a declaration for 'memset'
2 warnings generated.
```

**Comment by laanwj** [comment]
Interestingly, I don't see this warning when compiling secp256k1 stand-alone, even though it should (`-pedantic -Wall`).

**Comment by paveljanik** [comment]
I think it depends on the compiler. In my case, it was

```
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
```

**Comment by laanwj** [comment]
I compile with clang (3.9) too. I see the warning when compiling bitcoin w/ https://github.com/bitcoin/bitcoin/issues/8453, but not when compiling this library independently.

**Comment by paveljanik** [comment]
gcc-4.8.3 on openSUSE:

```
In file included from src/secp256k1.c:14:0:
src/ecmult_impl.h: In function 'secp256k1_ecmult_context_clone':
src/ecmult_impl.h:186:9: warning: implicit declaration of function 'memcpy' [-Wimplicit-function-declaration]
         memcpy(dst->pre_g, src->pre_g, size);
         ^
src/ecmult_impl.h:186:9: warning: incompatible implicit declaration of built-in function 'memcpy' [enabled by default]
src/ecmult_impl.h: In function 'secp256k1_ecmult_wnaf':
src/ecmult_impl.h:230:5: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
     memset(wnaf, 0, len * sizeof(wnaf[0]));
     ^
src/ecmult_impl.h:230:5: warning: incompatible implicit declaration of built-in function 'memset' [enabled by default]
```

All logs here are from standalone compile.

**Comment by laanwj** [comment]
Narrowed it down to `libsecp256k1-config.h`. When I copy the one from my bitcoin directory I get the warnings.
