### ISSUE TITLE
Regression.Code fails to compile with gcc 6.3

### ISSUE THREAD

**Issue by Raulo** [bitcoin-core/secp256k1#492]
Last commit f54c6c5 enabled benchmark building by default. Unfortunately, this code does not compile on my Ubuntu 16.04.

$ gcc --version
gcc (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519

src/bench_recover.c:18:6: error: ‘bench_recover’ redeclared as different kind of symbol
 void bench_recover(void* arg) {
      ^~~~~~~~~~~~~
src/bench_recover.c:16:3: note: previous declaration of ‘bench_recover’ was here
 } bench_recover;
   ^~~~~~~~~~~~~
src/bench_recover.c: In function ‘bench_recover’:
src/bench_recover.c:20:20: error: ‘data’ undeclared (first use in this function)
     bench_recover *data = (bench_recover*)arg;
                    ^~~~
src/bench_recover.c:20:20: note: each undeclared identifier is reported only once for each function it appears in
src/bench_recover.c:20:42: error: expected expression before ‘)’ token
     bench_recover *data = (bench_recover*)arg;
                                          ^
src/bench_recover.c:21:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     secp256k1_pubkey pubkey;
     ^~~~~~~~~~~~~~~~
src/bench_recover.c:18:26: warning: unused parameter ‘arg’ [-Wunused-parameter]
 void bench_recover(void* arg) {
                          ^~~
src/bench_recover.c: In function ‘bench_recover_setup’:
src/bench_recover.c:41:20: error: ‘data’ undeclared (first use in this function)
     bench_recover *data = (bench_recover*)arg;
                    ^~~~
src/bench_recover.c:41:42: error: expected expression before ‘)’ token
     bench_recover *data = (bench_recover*)arg;
                                          ^
src/bench_recover.c:39:32: warning: unused parameter ‘arg’ [-Wunused-parameter]
 void bench_recover_setup(void* arg) {
                                ^~~
src/bench_recover.c: In function ‘main’:
src/bench_recover.c:52:5: warning: statement with no effect [-Wunused-value]
     bench_recover data;
     ^~~~~~~~~~~~~
src/bench_recover.c:52:19: error: expected ‘;’ before ‘data’
     bench_recover data;
                   ^~~~
src/bench_recover.c:54:5: error: ‘data’ undeclared (first use in this function)
     data.ctx = secp256k1_context_create(SECP256K1_CONTEXT_VERIFY);
     ^~~~
Makefile:1009: recipe for target 'src/bench_recover.o' failed
make: *** [src/bench_recover.o] Error 1

Switching off the benchmark build with --enable-benchmark=no results in a clean compile.

**Comment by sipa** [comment]
Fixed by #490.
