### PR TITLE
contexts: Forbid destroying, cloning and randomizing the static context 

### PR DESCRIPTION
**Pull request by real-or-random**
As discussed in #1126.

For randomization, this has a history. Initially, this threw the illegal callback but then we changed it to be a no-op on non-signing contexts: https://github.com/bitcoin-core/secp256k1/commit/6198375218b8132f016b701ef049fb295ca28c95 But this was with (non-static) none/verification contexts in mind, not with the static context. If we anyway forbid cloning the static context, you should never a way to randomize a copy of the static context. (You need a copy because the static context itself is not writable. But you cannot obtain a copy except when using memcpy etc.)

### CODE REVIEW

**Comment by real-or-random** [comment]
force-pushed to clarify a comment and fix a commit message, ready for review

**Comment by real-or-random** [comment]
.... should be fixed. (If you think you can write a single line of code without rerunning the tests...)

**Comment by real-or-random** [comment]
> Are these perhaps still some cleanups from this PR we'd want?

The second commit is certainly a (tiny) fix. We should abort the API function (with `return`) for the case that a callback returns (callbacks aren't supposed to return but yeah.)  

Let me create a PR that doesn't have the breaking API changes and the test changes.

**Comment by real-or-random** [comment]
> Let me create a PR that doesn't have the breaking API changes and the test changes.

#1171, marking this one a draft.

**Comment by real-or-random** [comment]
(force-pushed a rebased version here but please ignore... the plan is to get #1186 merged first and then I need to reapply the interesting commits from here on top of it)

**Comment by real-or-random** [comment]
Ready for review.

I should have done the last commit first, but I want to avoid the effort to reorder unless someone insists.

**Comment by real-or-random** [comment]
force-pushed to make LSan happy (hopefully)

File: src/tests.c [hunk 1]
```diff
@@ -247,7 +247,16 @@ static void run_static_context_tests(int use_prealloc) {
 
     {
         int ecount = 0;
+        unsigned char seed[32] = {0x17};
         secp256k1_context_set_illegal_callback(STATIC_CTX, counting_illegal_callback_fn, &ecount);
+
```
Comment (apoelstra) [inline src/tests.c:277]: In d2e9636230e58f23282418d17b973645f792693e:

trailing whitespace

File: src/tests.c [hunk 2]
```diff
@@ -44,6 +44,33 @@ static int all_bytes_equal(const void* s, unsigned char value, size_t n) {
...
+}
+
+/* For checking functions that use ARG_CHECK */
+#define CHECK_ILLEGAL(ctx, expr) do { \
+    ILLEGAL = 0; \
+    secp256k1_context_set_illegal_callback(ctx, check_illegal_helper_callback_fn, NULL); \
+    { CHECK((expr) == 0); }                                       \
+    secp256k1_context_set_illegal_callback(ctx, NULL, NULL); \
+    CHECK(ILLEGAL == 1); \
+} while(0);
```
[the remark this answers is not in the document]
Comment (real-or-random) [reply src/tests.c:62]: Yeah, I had feared this makes the job of the optimizer harder, but maybe that concern is unnecessary (or even wrong).

I'll fix it.

[the remark this answers is not in the document]
Comment (apoelstra) [reply src/tests.c:62]: It probably will make the optimizer's job harder but I doubt it'll be noticeable, and these are only unit tests.

[the remark this answers is not in the document]
Comment (real-or-random) [reply src/tests.c:62]: fixed

**Comment by apoelstra** [comment]
It looks like 13ac8fa2b198e69b826ad241f4291195f5c9c4b4 doesn't compile on its own.
```
                                                                                                                                
2023-01-18T14:44:03 13ac8fa2 (232): Command failed: make -j8                                                                                                                                                                     
2023-01-18T14:44:03 13ac8fa2 (232): In file included from src/assumptions.h:12,                                                                                                                                                  
                 from src/secp256k1.c:23,                                                                                                                                                                                        
                 from src/tests.c:13:                                                                                                                                                                                            
src/tests.c: In function ‘run_proper_context_tests’:                                                                                                                                                                             
src/tests.c:346:30: error: ‘my_ctx_fresh’ undeclared (first use in this function)                                                                                                                                                
  346 |     CHECK(context_eq(my_ctx, my_ctx_fresh));                                                                                                                                                                             
      |                              ^~~~~~~~~~~~                                                                                                                                                                                
src/util.h:69:39: note: in definition of macro ‘EXPECT’                                                                                                                                                                          
   69 | #define EXPECT(x,c) __builtin_expect((x),(c))                                                                                                                                                                            
      |                                       ^                                                                                                                                                                                  
src/tests.c:346:5: note: in expansion of macro ‘CHECK’                                                                                                                                                                           
  346 |     CHECK(context_eq(my_ctx, my_ctx_fresh));                                                                                                                                                                             
      |     ^~~~~                                                                                                                                                                                                                
src/tests.c:346:30: note: each undeclared identifier is reported only once for each function it appears in                                                                                                                       
  346 |     CHECK(context_eq(my_ctx, my_ctx_fresh));                                                                                                                                                                             
      |                              ^~~~~~~~~~~~                                                                                                                                                                                src/util.h:69:39: note: in definition of macro ‘EXPECT’                                                                                                                                                                          
   69 | #define EXPECT(x,c) __builtin_expect((x),(c))                                                                                                                                                                            
      |                                       ^                                                                                                                                                                                  
src/tests.c:346:5: note: in expansion of macro ‘CHECK’                                                                                                                                                                           
  346 |     CHECK(context_eq(my_ctx, my_ctx_fresh));                                                                                                                                                                             
      |     ^~~~~                                                                                                                                                                                                                
In file included from src/assumptions.h:12,                                                                                                                                                                                      
                 from src/secp256k1.c:23,                                                                                                                                                                                        
                 from src/tests.c:13:                                                                              
```

**Comment by real-or-random** [comment]
Ooops, that line ended up in the wrong commit after rebasing. Should be fixed!

**Review by apoelstra — APPROVED** [review]
ACK 68622799302d4c6d2189f5bdf6f48bc54872363a

File: src/tests.c [hunk 3]
```diff
@@ -44,11 +44,35 @@ static int all_bytes_equal(const void* s, unsigned char value, size_t n) {
...
 
+/* TODO Use CHECK_ILLEGAL(_VOID) everywhere and get rid of the uncounting callback */
+/* For checking functions that use ARG_CHECK */
+#define CHECK_ILLEGAL(ctx, expr) do { \
+    /* long descriptive variable name to avoid accidental shadowing and have clear error message */ \
+    int32_t count_of_calls_to_illegal_callback = 0; \
+    secp256k1_context_set_illegal_callback(ctx, \
+        counting_illegal_callback_fn, &count_of_calls_to_illegal_callback); \
+    { CHECK((expr) == 0); } \
+    secp256k1_context_set_illegal_callback(ctx, NULL, NULL); \
```
[the remark this answers is not in the document]
Comment (real-or-random) [reply src/tests.c:55]: Hm, yes, it should probably do that!  (It feels a bit unclean to have a public setter function but not a getter. But I don't think we want one... If you ask me, [I'd rather would like to get rid of dynamic callbacks entirely](https://github.com/bitcoin-core/secp256k1/issues/780#issuecomment-675372163), though I'm not sure yet how this interacts with tests.)

[the remark this answers is not in the document]
Comment (real-or-random) [reply src/tests.c]: done, and also improved the macro defs a bit further

**Review by apoelstra — APPROVED** [review]
ACK e39d954f118a29db2c33e9a9a507053fff5573ed
