### ISSUE TITLE
Arm ASM builds are broken

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-core/secp256k1#931]
Gen_context tries to use ASM but doesn't get linked against it:

```
gcc -O2 -fvisibility=hidden -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-unused-function -Wno-long-long -Wno-overlength-strings -W -g  gen_context.o -o gen_context
gen_context.o: In function `secp256k1_fe_mul':
/home/gmaxwell/secp256k1/src/field_10x26_impl.h:1078: undefined reference to `secp256k1_fe_mul_inner'
gen_context.o: In function `secp256k1_fe_sqr':
/home/gmaxwell/secp256k1/src/field_10x26_impl.h:1091: undefined reference to `secp256k1_fe_sqr_inner'
/home/gmaxwell/secp256k1/src/field_10x26_impl.h:1091: undefined reference to `secp256k1_fe_sqr_inner'
/home/gmaxwell/secp256k1/src/field_10x26_impl.h:1091: undefined reference to `secp256k1_fe_sqr_inner'
/home/gmaxwell/secp256k1/src/field_10x26_impl.h:1091: undefined reference to `secp256k1_fe_sqr_inner'
...
```

Reverting a3aa2628c7b675814157556d774872755c9f1aba fixes it.

**Comment by sipa** [comment]
Related: going to work on adding ARM32/ARM64 CI in #930 so that these things don't silently break.
